name: Main

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Graph
        run: npx -p @mermaid-js/mermaid-cli mmdc -i input.mmd -o graph.pdf

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: bundle
          name: bundle name
          body: description
          draft: false
          prerelease: false
          files: graph.pdf